import "~/styles/globals.css";
import { Toaster } from "sonner";


export const metadata = {
  title: "Create Todo App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <Toaster />
      <body style={{ fontFamily: "sans-serif" }} >{children}</body>
    </html>
  );
}
